\set POSTGRES_AUTHENTIK_USER 'authentik'
\set POSTGRES_AUTHENTIK_PASSWORD `printf -- '%s' "${POSTGRES_AUTHENTIK_PASSWORD}"`
\set POSTGRES_AUTHENTIK_DATABASE 'authentik'

CREATE USER :"POSTGRES_AUTHENTIK_USER" PASSWORD :'POSTGRES_AUTHENTIK_PASSWORD';
CREATE DATABASE :"POSTGRES_AUTHENTIK_DATABASE" WITH OWNER = :"POSTGRES_AUTHENTIK_USER" ENCODING = 'UTF8' TABLESPACE = pg_default;
GRANT ALL PRIVILEGES ON DATABASE :"POSTGRES_AUTHENTIK_DATABASE" TO :"POSTGRES_AUTHENTIK_USER";

\connect :"POSTGRES_AUTHENTIK_DATABASE" :"POSTGRES_AUTHENTIK_USER"
