\set POSTGRES_DEX_USER 'dex'
\set POSTGRES_DEX_PASSWORD `printf -- '%s' "${POSTGRES_DEX_PASSWORD}"`
\set POSTGRES_DEX_DATABASE 'dex'

CREATE USER :"POSTGRES_DEX_USER" PASSWORD :'POSTGRES_DEX_PASSWORD';
CREATE DATABASE :"POSTGRES_DEX_DATABASE" WITH OWNER = :"POSTGRES_DEX_USER" ENCODING = 'UTF8' TABLESPACE = pg_default;
GRANT ALL PRIVILEGES ON DATABASE :"POSTGRES_DEX_DATABASE" TO :"POSTGRES_DEX_USER";

\connect :"POSTGRES_DEX_DATABASE" :"POSTGRES_DEX_USER"
