\set POSTGRES_GRAFANA_USER `printf -- '%s' "${POSTGRES_GRAFANA_USER:-grafana}"`
\set POSTGRES_GRAFANA_PASSWORD `printf -- '%s' "${POSTGRES_GRAFANA_PASSWORD:?}"`
\set POSTGRES_GRAFANA_DATABASE `printf -- '%s' "${POSTGRES_GRAFANA_DATABASE:-grafana}"`

CREATE USER :"POSTGRES_GRAFANA_USER" PASSWORD :'POSTGRES_GRAFANA_PASSWORD';
CREATE DATABASE :"POSTGRES_GRAFANA_DATABASE" WITH OWNER = :"POSTGRES_GRAFANA_USER" ENCODING = 'UTF8' TABLESPACE = pg_default;
GRANT ALL PRIVILEGES ON DATABASE :"POSTGRES_GRAFANA_DATABASE" TO :"POSTGRES_GRAFANA_USER";

\connect :"POSTGRES_GRAFANA_DATABASE" :"POSTGRES_GRAFANA_USER"
