# yaml-language-server: $schema=https://version-2024-8.goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: "Branding"
  labels:
    blueprints.goauthentik.io/description: "Branding"
    blueprints.goauthentik.io/instantiate: "true"
entries:
  # Apply "Default - Brand" blueprint
  - model: "authentik_blueprints.metaapplyblueprint"
    identifiers: {}
    attrs:
      identifiers:
        name: "Default - Brand"
      required: true
  # Apply "Default - Authentication flow" blueprint
  - model: "authentik_blueprints.metaapplyblueprint"
    identifiers: {}
    attrs:
      identifiers:
        name: "Default - Authentication flow"
      required: true
  # Apply branding to default brand
  - id: "default-brand"
    identifiers:
      domain: "authentik-default"
    model: "authentik_brands.brand"
    attrs:
      branding_title: "authentik"
      branding_logo: "/static/dist/custom/blank.png"
      branding_default_flow_background: "/static/dist/custom/blank.png"
      branding_favicon: "/static/dist/assets/icons/icon.png"
      branding_custom_css: |
        .pf-c-login__main-header.pf-c-brand.ak-brand {
          display: none;
        }

        .ak-login-container {
          gap: 1rem;
          justify-content: center;
        }

        .pf-c-login__main, .pf-c-login__footer {
          margin: 0;
          flex: 0;
        }
      attributes:
        settings:
          enabledFeatures:
            applicationEdit: false
            search: false
          theme:
            base: "automatic"
  # Apply branding to default authentication flow
  - id: "default-authentication-flow"
    identifiers:
      slug: "default-authentication-flow"
    model: "authentik_flows.flow"
    attrs:
      title: "Sign in to your account"
