# yaml-language-server: $schema=https://version-2023-4.goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: "Grist configuration"
  labels:
    blueprints.goauthentik.io/description: "Grist configuration"
    blueprints.goauthentik.io/instantiate: "true"
entries:
  # Apply "Default - Events Transport & Rules" blueprint
  - model: "authentik_blueprints.metaapplyblueprint"
    attrs:
      identifiers:
        name: "Default - Events Transport & Rules"
      required: true
  # Apply "Default - Authentication flow" blueprint
  - model: "authentik_blueprints.metaapplyblueprint"
    attrs:
      identifiers:
        name: "Default - Authentication flow"
      required: true
  # Apply "Default - Provider authorization flow (explicit consent)" blueprint
  - model: "authentik_blueprints.metaapplyblueprint"
    attrs:
      identifiers:
        name: "Default - Provider authorization flow (explicit consent)"
      required: true
  # Apply "System - OAuth2 Provider - Scopes" blueprint
  - model: "authentik_blueprints.metaapplyblueprint"
    attrs:
      identifiers:
        name: "System - OAuth2 Provider - Scopes"
      required: true
  # Apply "Groups configuration" blueprint
  - model: "authentik_blueprints.metaapplyblueprint"
    attrs:
      identifiers:
        name: "Groups configuration"
      required: true
  # Apply "JWT certificate" blueprint
  - model: "authentik_blueprints.metaapplyblueprint"
    attrs:
      identifiers:
        name: "JWT certificate"
      required: true
  # Grist provider
  - id: "grist-provider"
    identifiers:
      name: "Grist"
    model: "authentik_providers_oauth2.oauth2provider"
    attrs:
      name: "Grist"
      authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
      client_type: "confidential"
      client_id: "grist"
      client_secret: !Env GRIST_OAUTH_CLIENT_SECRET
      redirect_uris: !Format [https://%s/.*, !Env GRIST_DOMAIN]
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, JWT certificate]]
      access_code_validity: "minutes=1"
      access_token_validity: "minutes=5"
      refresh_token_validity: "days=30"
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-email]]
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-profile]]
      sub_mode: "hashed_user_id"
      include_claims_in_id_token: true
      issuer_mode: "per_provider"
  # Grist application
  - id: "grist-application"
    identifiers:
      name: "Grist"
    model: "authentik_core.application"
    attrs:
      name: "Grist"
      slug: "grist"
      provider: !KeyOf grist-provider
      policy_engine_mode: "any"
      meta_publisher: "Grist Labs"
      meta_launch_url: !Format [https://%s, !Env GRIST_DOMAIN]
      icon: "/static/dist/custom/icons/grist.svg"
  # Grist application admin group policy binding
  - identifiers:
      target: !Find [authentik_core.application, [name, Grist]]
      group: !Find [authentik_core.group, [name, authentik Admins]]
    model: "authentik_policies.policybinding"
    attrs:
      target: !Find [authentik_core.application, [name, Grist]]
      group: !Find [authentik_core.group, [name, authentik Admins]]
      enabled: true
      order: 0
  # Grist application person group policy binding
  - identifiers:
      target: !Find [authentik_core.application, [name, Grist]]
      group: !Find [authentik_core.group, [name, person]]
    model: "authentik_policies.policybinding"
    attrs:
      target: !Find [authentik_core.application, [name, Grist]]
      group: !Find [authentik_core.group, [name, person]]
      enabled: true
      order: 10
