# yaml-language-server: $schema=https://version-2023-4.goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: "Sample users"
  labels:
    blueprints.goauthentik.io/description: "Sample users"
    blueprints.goauthentik.io/instantiate: "false"
entries:
  # Apply "Groups configuration" blueprint
  - model: "authentik_blueprints.metaapplyblueprint"
    attrs:
      identifiers:
        name: "Groups configuration"
      required: true
  # Sample users
  - id: "sample-user-alice"
    identifiers:
      username: "alice"
    model: "authentik_core.user"
    attrs:
      username: "alice"
      name: "Alice Bennett"
      email: "alice@example.localhost"
      password: "password"
      is_active: true
      path: "users"
      groups:
        - !Find [authentik_core.group, [name, person]]
  - id: "sample-user-bob"
    identifiers:
      username: "bob"
    model: "authentik_core.user"
    attrs:
      username: "bob"
      name: "Bob Collins"
      email: "bob@example.localhost"
      password: "password"
      is_active: true
      path: "users"
      groups:
        - !Find [authentik_core.group, [name, person]]
  - id: "sample-user-carol"
    identifiers:
      username: "carol"
    model: "authentik_core.user"
    attrs:
      username: "carol"
      name: "Carol Davis"
      email: "carol@example.localhost"
      password: "password"
      is_active: true
      path: "users"
      groups:
        - !Find [authentik_core.group, [name, person]]
  - id: "sample-user-dan"
    identifiers:
      username: "dan"
    model: "authentik_core.user"
    attrs:
      username: "dan"
      name: "Dan Edwards"
      email: "dan@example.localhost"
      password: "password"
      is_active: true
      path: "users"
      groups:
        - !Find [authentik_core.group, [name, person]]
  - id: "sample-user-erin"
    identifiers:
      username: "erin"
    model: "authentik_core.user"
    attrs:
      username: "erin"
      name: "Erin Fisher"
      email: "erin@example.localhost"
      password: "password"
      is_active: true
      path: "users"
      groups:
        - !Find [authentik_core.group, [name, person]]
  - id: "sample-user-frank"
    identifiers:
      username: "frank"
    model: "authentik_core.user"
    attrs:
      username: "frank"
      name: "Frank Graham"
      email: "frank@example.localhost"
      password: "password"
      is_active: true
      path: "users"
      groups:
        - !Find [authentik_core.group, [name, person]]
